name: Deploy Backend to Azure

##Déclanchement du workflow -> lorque un push est effectué sur la branche main, cella déclanche le workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  ## worflow_dispatch permet de lancer le workflow depuis l'interface GitHUb
## Job build -> construction et dépploiement de l'application
jobs:
  build:
    runs-on: ubuntu-latest
    ## récupéré le code source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

