# This workflow will build a Golang project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-exoscale-image

on:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"

env:
  REGISTRY_NAME: "exo.container-registry.com"
  REPOSITORY_NAME: "todo-app"  # Assurez-vous que cette variable est bien définie

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Configuration de Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Verify Go installation
        run: go version

      # Étape 3: Build de l'image Docker
      - name: Build Docker image
        working-directory: ./src/backend
        run: docker build -t todo-app .

      # Étape 4: Connexion à la registry Docker avec les secrets
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Secret pour le nom d'utilisateur
          password: ${{ secrets.DOCKER_PASSWORD }}  # Secret pour le token

      # Étape 5: Taguer l'image avec le tag approprié
      - name: Tag Docker image
        run: docker tag todo-app ${{ env.REGISTRY_NAME }}/${{ env.REPOSITORY_NAME }}:AH

      # Étape 6: Pousser l'image vers la registry
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY_NAME }}/${{ env.REPOSITORY_NAME }}:AH
