# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebApp-300622-axellehertig

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300622210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_694ca957c8564d1aa629ccdd37a28074 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d72d59ff899549b7a485153053786855 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694ca957c8564d1aa629ccdd37a28074 }}/todo-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-300622-axellehertig'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3857daebe50c4622945b886c671218c8 }}
        images: 'acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694ca957c8564d1aa629ccdd37a28074 }}/todo-app:${{ github.sha }}'